name: Build

on: [push, pull_request]

env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}
  GCE_INSTANCE: ${{ secrets.GCE_INSTANCE }}
  GCE_INSTANCE_ZONE: ${{ secrets.GCE_INSTANCE_ZONE }}

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
    - name: "Connect to VM"
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.GCE_HOST }}
        username: ${{ secrets.GCE_USERNAME }}
        key: ${{ secrets.GCE_KEY }}
        script: |
          cd ${{ secrets.GCE_DEPLOYMENT_PATH }}/orchestrator-new-frontend-js && sudo git pull origin master && cd ${{ secrets.GCE_DEPLOYMENT_PATH }}/orchestrator-nginx-gateway
          sudo docker compose up -d --build orch-front
